### ISSUE TITLE
Default variable values

### ISSUE THREAD

**Issue by macat** [namely/broadway#75]
Playbooks should be able to declare default values for variables.

Current syntax:
```yaml
vars:
  - version
  - database
```

Proposed syntax:
```yaml
vars:
  version: "0.1"
  database:
```

**Comment by bobbytables** [comment]
Making it a hash isn't backwards compatible.

**Comment by bobbytables** [comment]
If we wanted we could get super crazy with this too:

```
vars:
  - database_url={{ .playbook_id }}-postgres
```

**Comment by macat** [comment]
Why not backwards compatible?

**Comment by bobbytables** [comment]
Because an array isn't a hash 💩

**Comment by macat** [comment]
We could still allow using a list in playbooks.

**Comment by bobbytables** [comment]
What would that look like
?

**Comment by macat** [comment]
Broadway doesn't have a ton of users, so I wouldn't worry about changing it to a hash. But we could make it parse as a list or a hash.

**Comment by macat** [comment]
We can use variables with hashes too.. if we really want to get crazy.
```
vars:
  test: "ok-{{ .playbook_id }}"
```

**Comment by bobbytables** [comment]
It would look like this I suppose, which is backwards compatible:

```yaml
vars:
  - value
  - var2: default
```

**Comment by macat** [comment]
That's basically a list of hashes

**Comment by bobbytables** [comment]
Naw it'll interpolate, I tried it:

```json
{
  "vars": [
    "value", 
    {
      "var2": "default"
    }
  ]
}
```

**Comment by macat** [comment]
That's not too bad.

**Comment by bobbytables** [comment]
Ok so my official proposal is this:

```yml
vars:
  - variable1
  - variable2
  - variable3: default-value
  - variable4: {{ .playbook_id }}-lolok
```
